<a href="https://colab.research.google.com/github/AkshayMetry/AkshayMetry/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resources

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
#Pytorch Fundamentals
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#print(torch.__version__)

Introduction To Tensors

Creating tensors

In [2]:
#scalars
#torch.Tensor - A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector - Magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [9]:
#MATRIX
MATRIX = torch.tensor([ [7,8],
                        [8,7] ])
MATRIX

tensor([[7, 8],
        [8, 7]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([8, 7])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,4,6]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [18]:
TENSOR[0][1]

tensor([4, 5, 6])

In [19]:
# Randoms Tensors

#Randoms tensors are imp because the way many neural network learn is that they start
#with tensors full of random numbers and then adjust those random numbers to bettter represent the data.

# Start with random number --> look at data --> update random numbers --> look at data --> update random numbers

