<a href="https://colab.research.google.com/github/AkshayMetry/AkshayMetry/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resources

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
#Pytorch Fundamentals
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#print(torch.__version__)

Introduction To Tensors

Creating tensors

In [2]:
#scalars
#torch.Tensor - A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector - Magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
#MATRIX
MATRIX = torch.tensor([ [7,8],
                        [8,7] ])
MATRIX

tensor([[7, 8],
        [8, 7]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([8, 7])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,4,6]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [16]:
TENSOR[0][1]

tensor([4, 5, 6])

In [17]:
# Randoms Tensors

#Randoms tensors are imp because the way many neural network learn is that they start
#with tensors full of random numbers and then adjust those random numbers to bettter represent the data.

# Start with random number --> look at data --> update random numbers --> look at data --> update random numbers


#Create a random tensor of size
# https://pytorch.org/docs/stable/generated/torch.rand.html
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6334, 0.9491, 0.2142, 0.1726],
        [0.2696, 0.1216, 0.2529, 0.6123],
        [0.8702, 0.2810, 0.6115, 0.5088]])

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_tensor.ndim

2

In [20]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3,224,224)) #height, width, color channel
random_image_tensor

tensor([[[0.0256, 0.6139, 0.4950,  ..., 0.9770, 0.8164, 0.0494],
         [0.8508, 0.6068, 0.8728,  ..., 0.4420, 0.7213, 0.7184],
         [0.7183, 0.1677, 0.6437,  ..., 0.2964, 0.0178, 0.7863],
         ...,
         [0.6989, 0.7431, 0.5719,  ..., 0.5833, 0.7343, 0.7634],
         [0.5145, 0.7608, 0.5734,  ..., 0.3286, 0.9343, 0.7422],
         [0.2554, 0.8061, 0.9037,  ..., 0.6956, 0.8985, 0.1819]],

        [[0.1318, 0.1624, 0.8295,  ..., 0.9053, 0.4044, 0.5329],
         [0.7661, 0.7575, 0.8702,  ..., 0.1525, 0.8954, 0.9224],
         [0.2801, 0.7127, 0.9180,  ..., 0.3245, 0.3540, 0.6518],
         ...,
         [0.3734, 0.7314, 0.1638,  ..., 0.7501, 0.5628, 0.5524],
         [0.5254, 0.7774, 0.0413,  ..., 0.2179, 0.8846, 0.2788],
         [0.0416, 0.2207, 0.9979,  ..., 0.5996, 0.6006, 0.7212]],

        [[0.4141, 0.0347, 0.2161,  ..., 0.6566, 0.6852, 0.6149],
         [0.3513, 0.0185, 0.8373,  ..., 0.0629, 0.1389, 0.4222],
         [0.2058, 0.6844, 0.9610,  ..., 0.6834, 0.2902, 0.

In [21]:
# Zero and Ones
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_image_tensor.dtype

torch.float32

In [25]:
# Creating a range of tensors and tensors-like
#Use torch.range()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# Tensors datatypes

## Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
# 1. Tensors not right datatype
# 2. Tensors not right shape
# 3. Tensors not on the right device

# Float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None, #what datatype is tensor - float32, float16
                                device = None, #what device is your tensor on
                                requires_grad=False) #whether or not to track gradients with tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)